version: '3.7'

services:
  app:
#    image: michelep98/time-tracker:latest раскомментируйте эту строку и закомментируйте 3 следующие строки, если хотите загрузить образ из dockerhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/time-tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
  db:
    image: postgres:15.8
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - tt-database_data:/var/lib/postgresql/data2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time-tracker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  tt-database_data: