version: '3.7'

services:
  db:
    image: postgres:15.8
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - tt-database_data:/var/lib/postgresql/data2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time-tracker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  tt-database_data: