spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time-tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        open-in-view: false
        default_schema: time